#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Always operate from the repo root, wherever the human invoked us from.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Captured values land in the gitignored local profile, never in the tracked
# application.properties. Spring reads this file only with the "local" profile.
ENV_FILE="src/main/resources/application-local.properties"

MYSQL_CONTAINER="yanif-mysql"
MYSQL_IMAGE="mysql:8.4"
MYSQL_DB="yanif"
MYSQL_PORT="3306"
REDIS_CONTAINER="yanif-redis"
REDIS_IMAGE="redis:7-alpine"
REDIS_PORT="6379"

# prop KEY echoes the value already in ENV_FILE, if any. Dots stay literal.
prop() {
  local key_re line
  if [[ ! -f "$ENV_FILE" ]]; then return 1; fi
  key_re=${1//./\\.}
  line=$(grep -E "^${key_re}=" "$ENV_FILE" 2>/dev/null | tail -n1) || return 1
  if [[ -z "$line" ]]; then return 1; fi
  printf '%s' "${line#*=}"
}

# ensure_env_file creates the local profile with a header the first time.
ensure_env_file() {
  if [[ -f "$ENV_FILE" ]]; then return 0; fi
  mkdir -p "$(dirname "$ENV_FILE")"
  {
    printf '# Local dev overrides for Yanif, generated by scripts/dev-setup.sh\n'
    printf '# Gitignored. Spring loads this only when the "local" profile is active:\n'
    printf '#   ./mvnw spring-boot:run -Dspring-boot.run.profiles=local\n\n'
  } > "$ENV_FILE"
}

banner "Yanif local dev setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: toolchain"
say "Checking what the project needs. Nothing is changed in this stage."
printf '\n'

PREFLIGHT_FAIL=0

if docker info >/dev/null 2>&1; then
  note "docker   $(docker --version 2>/dev/null || true)"
else
  warn "Docker isn't responding. Start Docker Desktop, then re-run."
  PREFLIGHT_FAIL=1
fi

if command -v java >/dev/null 2>&1; then
  JAVA_MAJOR=$( { java -version 2>&1 || true; } | head -1 | sed -E 's/^[^"]*"([0-9]+).*/\1/' )
  if [[ "$JAVA_MAJOR" =~ ^[0-9]+$ ]] && (( JAVA_MAJOR >= 21 )); then
    note "java     $JAVA_MAJOR  (pom.xml targets 21)"
  else
    warn "Java 21+ required; found '${JAVA_MAJOR:-unknown}'."
    PREFLIGHT_FAIL=1
  fi
else
  warn "No java on PATH. Install a JDK 21 or newer."
  PREFLIGHT_FAIL=1
fi

if command -v node >/dev/null 2>&1; then
  note "node     $(node --version 2>/dev/null || true)"
  note "npm      $(npm --version 2>/dev/null || true)"
else
  warn "No node on PATH. The frontend stage needs Node 18+."
  PREFLIGHT_FAIL=1
fi

if [[ -x ./mvnw ]]; then
  note "mvnw     present"
else
  warn "./mvnw is missing or not executable."
  PREFLIGHT_FAIL=1
fi

printf '\n'
if (( PREFLIGHT_FAIL )); then
  warn "Fix the above and re-run. Nothing has been changed."
  exit 1
fi
say "Toolchain looks good."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Redis: engine snapshots"
say "Every engine mutation is snapshotted to Redis, so a restart resumes games"
say "instead of re-dealing. Presence lives here too."
printf '\n'

ensure_env_file

# redis_ping CONTAINER [PASSWORD] echoes whatever the server replies, so the
# caller can tell PONG from NOAUTH from silence.
redis_ping() {
  if [[ -n "${2:-}" ]]; then
    docker exec "$1" redis-cli --no-auth-warning -a "$2" ping 2>/dev/null || true
  else
    docker exec "$1" redis-cli ping 2>/dev/null || true
  fi
}

REDIS_PW=""
EXISTING_REDIS_PW="$(prop 'spring.data.redis.password' || true)"
RUNNING_REDIS=$(docker ps --filter "publish=${REDIS_PORT}" --format '{{.Names}}' 2>/dev/null | head -1 || true)

if [[ -n "$RUNNING_REDIS" ]]; then
  note "container '${RUNNING_REDIS}' already publishes ${REDIS_PORT}"
  REDIS_REPLY="$(redis_ping "$RUNNING_REDIS")"

  if [[ "$REDIS_REPLY" == *PONG* ]]; then
    say "PONG. Reusing it, and it wants no password."

  elif [[ "$REDIS_REPLY" == *NOAUTH* ]]; then
    warn "This Redis requires a password, so the app needs it too."
    if [[ -n "$EXISTING_REDIS_PW" ]] && [[ "$(redis_ping "$RUNNING_REDIS" "$EXISTING_REDIS_PW")" == *PONG* ]]; then
      REDIS_PW="$EXISTING_REDIS_PW"
      note "the password already in ${ENV_FILE} still works"
    else
      for attempt in 1 2 3; do
        ask_secret REDIS_PW_INPUT "Redis password:"
        if [[ "$(redis_ping "$RUNNING_REDIS" "$REDIS_PW_INPUT")" == *PONG* ]]; then
          REDIS_PW="$REDIS_PW_INPUT"
          say "PONG. Password accepted."
          break
        fi
        warn "Rejected (attempt ${attempt}/3)."
      done
      if [[ -z "$REDIS_PW" ]]; then
        warn "Carrying on without it; snapshots will fail until it's set."
        SKIPPED+=("Redis password: add spring.data.redis.password to ${ENV_FILE}")
      fi
    fi

  else
    warn "'${RUNNING_REDIS}' holds ${REDIS_PORT} but didn't answer PING."
    warn "If that container isn't Redis, stop it before continuing."
    pause "Press Enter once ${REDIS_PORT} is serving Redis"
  fi
else
  say "No container is publishing ${REDIS_PORT}."
  if confirm "Start one now (${REDIS_IMAGE} as '${REDIS_CONTAINER}')?"; then
    docker run -d --name "$REDIS_CONTAINER" -p "${REDIS_PORT}:6379" "$REDIS_IMAGE" >/dev/null
    sleep 2
    if [[ "$(redis_ping "$REDIS_CONTAINER")" == *PONG* ]]; then
      say "PONG. '${REDIS_CONTAINER}' is up, with no password."
    else
      warn "Started '${REDIS_CONTAINER}' but PING failed. Check: docker logs ${REDIS_CONTAINER}"
      SKIPPED+=("a responding Redis on ${REDIS_PORT}")
    fi
  else
    warn "Skipping Redis. Games won't survive a server restart without it."
    SKIPPED+=("Redis on ${REDIS_PORT}")
  fi
fi

write_env "spring.data.redis.host" "localhost"
write_env "spring.data.redis.port" "$REDIS_PORT"
write_env "spring.redis.host" "localhost"
write_env "spring.redis.port" "$REDIS_PORT"

if [[ -n "$REDIS_PW" ]]; then
  write_env "spring.data.redis.password" "$REDIS_PW"
  write_env "spring.redis.password" "$REDIS_PW"
elif grep -qE '^spring\.(data\.)?redis\.password=' "$ENV_FILE" 2>/dev/null; then
  STALE_TMP="$(mktemp)"
  grep -vE '^spring\.(data\.)?redis\.password=' "$ENV_FILE" > "$STALE_TMP"
  mv "$STALE_TMP" "$ENV_FILE"
  note "dropped a stale Redis password from ${ENV_FILE}"
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "MySQL: persisted outcomes"
say "Users, games, rounds and friendships persist here. Live play does not."
say "Hibernate is on ddl-auto=update, so the schema builds itself on first boot."
printf '\n'

EXISTING_PW="$(prop 'spring.datasource.password' || true)"
MYSQL_STATE=$(docker ps -a --filter "name=^${MYSQL_CONTAINER}$" --format '{{.State}}' 2>/dev/null | head -1 || true)

if [[ "$MYSQL_STATE" == "running" ]]; then
  note "container '${MYSQL_CONTAINER}' is already running"
  if [[ -n "$EXISTING_PW" ]]; then
    MYSQL_PW="$EXISTING_PW"
    note "reusing the root password already in ${ENV_FILE}"
  else
    ask_secret MYSQL_PW_EXISTING "Root password for the running '${MYSQL_CONTAINER}':"
    MYSQL_PW="${MYSQL_PW_EXISTING:-root}"
  fi
  warn "Recreating this container DROPS every stored user, game and round."
  if confirm "Recreate '${MYSQL_CONTAINER}' from scratch (destroys its data)?"; then
    docker rm -f "$MYSQL_CONTAINER" >/dev/null
    MYSQL_STATE="absent"
  fi
elif [[ "$MYSQL_STATE" == "exited" || "$MYSQL_STATE" == "created" ]]; then
  note "container '${MYSQL_CONTAINER}' exists but is stopped. Starting it."
  docker start "$MYSQL_CONTAINER" >/dev/null
  MYSQL_PW="${EXISTING_PW:-root}"
  MYSQL_STATE="running"
fi

if [[ "$MYSQL_STATE" != "running" ]]; then
  if command -v lsof >/dev/null 2>&1 && lsof -nP -iTCP:"${MYSQL_PORT}" -sTCP:LISTEN >/dev/null 2>&1; then
    warn "Port ${MYSQL_PORT} is already held by something else."
    warn "Stop it, or this container won't be reachable."
    pause "Press Enter once ${MYSQL_PORT} is free"
  fi
  if [[ -n "$EXISTING_PW" ]]; then
    MYSQL_PW="$EXISTING_PW"
    note "reusing the root password already in ${ENV_FILE}"
  else
    ask_secret MYSQL_PW_NEW "Root password to set (Enter for 'root'):"
    MYSQL_PW="${MYSQL_PW_NEW:-root}"
  fi
  say "Starting ${MYSQL_IMAGE} as '${MYSQL_CONTAINER}' with database '${MYSQL_DB}'."
  docker run -d --name "$MYSQL_CONTAINER" \
    -p "${MYSQL_PORT}:3306" \
    -e MYSQL_ROOT_PASSWORD="$MYSQL_PW" \
    -e MYSQL_DATABASE="$MYSQL_DB" \
    "$MYSQL_IMAGE" >/dev/null
fi

say "Waiting for MySQL to accept connections (up to 90s)."
MYSQL_READY=0
for _ in $(seq 1 45); do
  if docker exec -e MYSQL_PWD="$MYSQL_PW" "$MYSQL_CONTAINER" \
       mysqladmin ping -uroot --silent >/dev/null 2>&1; then
    MYSQL_READY=1
    break
  fi
  sleep 2
done

if (( MYSQL_READY )); then
  docker exec -e MYSQL_PWD="$MYSQL_PW" "$MYSQL_CONTAINER" \
    mysql -uroot -e "CREATE DATABASE IF NOT EXISTS \`${MYSQL_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" \
    >/dev/null 2>&1 || true
  if docker exec -e MYSQL_PWD="$MYSQL_PW" "$MYSQL_CONTAINER" \
       mysql -uroot -N -e "SHOW DATABASES LIKE '${MYSQL_DB}';" 2>/dev/null | grep -q "$MYSQL_DB"; then
    say "database '${MYSQL_DB}' is present."
  else
    warn "Connected, but database '${MYSQL_DB}' is missing."
    SKIPPED+=("create the '${MYSQL_DB}' database")
  fi
else
  warn "MySQL never became ready. Check: docker logs ${MYSQL_CONTAINER}"
  SKIPPED+=("a reachable MySQL on ${MYSQL_PORT}")
fi

write_env "spring.datasource.url" "jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DB}?serverTimezone=UTC&useLegacyDatetimeCode=false"
write_env "spring.datasource.username" "root"
write_env "spring.datasource.password" "$MYSQL_PW"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "JWT signing secret"
say "The tracked application.properties ships a placeholder secret. Local dev"
say "gets its own, so the placeholder never signs a real token."
printf '\n'

EXISTING_JWT="$(prop 'app.jwt.secret' || true)"
if [[ -n "$EXISTING_JWT" ]]; then
  note "a secret is already set in ${ENV_FILE}"
  if confirm "Generate a fresh one (invalidates locally-issued tokens)?"; then
    EXISTING_JWT=""
  fi
fi

if [[ -z "$EXISTING_JWT" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    JWT_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
  else
    JWT_SECRET="$( { head -c 48 /dev/urandom || true; } | base64 | tr -d '\n')"
  fi
  say "generated a 64-character secret; the signer needs at least 32."
else
  JWT_SECRET="$EXISTING_JWT"
fi

write_env "app.jwt.secret" "$JWT_SECRET"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Wire up the local profile"
say "Everything captured so far lives in one gitignored file:"
note "  ${ENV_FILE}"
printf '\n'
say "Spring reads it only when the 'local' profile is active. Either:"
note "  ./mvnw spring-boot:run -Dspring-boot.run.profiles=local"
note "  export SPRING_PROFILES_ACTIVE=local     # once per shell"
printf '\n'
say "Contents, with secrets masked:"
printf '\n'
sed -E 's/^(app\.jwt\.secret=).*/\1********/;
        s/^(spring\.datasource\.password=).*/\1********/;
        s/^(spring\.(data\.)?redis\.password=).*/\1********/' "$ENV_FILE" \
  | sed 's/^/    /'
printf '\n'
pause "Press Enter once that looks right"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Git hooks: keep the engine docs honest"
say "A commit touching game/, GameStateController or a game.* property is"
say "rejected unless docs/game-engine.md changes in the same commit."
printf '\n'

if [[ -x scripts/install-hooks.sh ]]; then
  if confirm "Install the pre-commit hook now?"; then
    ./scripts/install-hooks.sh
    note "bypass a genuinely doc-neutral commit with: git commit --no-verify"
  else
    SKIPPED+=("git hooks (./scripts/install-hooks.sh)")
  fi
elif [[ -f scripts/install-hooks.sh ]]; then
  warn "scripts/install-hooks.sh isn't executable."
  SKIPPED+=("git hooks (chmod +x scripts/install-hooks.sh && ./scripts/install-hooks.sh)")
else
  note "scripts/install-hooks.sh isn't on this branch. Skipping."
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Frontend dependencies"
say "The React client builds into the backend's static resources, so one JAR"
say "serves everything. In dev it runs separately and proxies to :8080."
printf '\n'

if [[ -d frontend/node_modules ]] && [[ -n "$(ls -A frontend/node_modules 2>/dev/null || true)" ]]; then
  note "frontend/node_modules is already populated"
else
  say "frontend/node_modules is empty."
  if confirm "Run 'npm ci' in frontend/ now (takes a few minutes)?"; then
    if ( cd frontend && npm ci ); then
      say "dependencies installed."
    else
      warn "npm ci failed. Scroll up for the reason."
      SKIPPED+=("frontend deps (cd frontend && npm ci)")
    fi
  else
    SKIPPED+=("frontend deps (cd frontend && npm ci)")
  fi
fi

printf '\n'
say "The e2e suite drives Playwright's chromium project."
if confirm "Install the Playwright chromium browser?"; then
  if ( cd frontend && npx playwright install chromium ); then
    say "chromium installed."
  else
    warn "Playwright install failed."
    SKIPPED+=("Playwright browser (cd frontend && npx playwright install chromium)")
  fi
else
  SKIPPED+=("Playwright browser (cd frontend && npx playwright install chromium)")
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Verify"
say "Backend tests run on H2 under the 'test' profile, so they need no"
say "containers. They prove the rules engine, not the wiring."
printf '\n'

if confirm "Run ./mvnw test now?"; then
  if ./mvnw -q test; then
    say "backend tests passed."
  else
    warn "Backend tests failed. Scroll up for the first failure."
    SKIPPED+=("a green ./mvnw test")
  fi
else
  SKIPPED+=("./mvnw test")
fi

printf '\n'
say "A boot check is what proves MySQL, Redis and the local profile wire up."
if confirm "Boot on :8080 and hit /api/v1/version?"; then
  BOOT_LOG="$(mktemp -t yanif-boot)"
  ./mvnw -q spring-boot:run \
    -Dspring-boot.run.profiles=local \
    -Dspring-boot.run.fork=false >"$BOOT_LOG" 2>&1 &
  BOOT_PID=$!
  BOOTED=0
  for _ in $(seq 1 60); do
    if curl -fsS http://localhost:8080/api/v1/version >/dev/null 2>&1; then
      BOOTED=1
      break
    fi
    kill -0 "$BOOT_PID" 2>/dev/null || break
    sleep 2
  done
  if (( BOOTED )); then
    say "/api/v1/version -> $(curl -fsS http://localhost:8080/api/v1/version 2>/dev/null || true)"
  else
    warn "Nothing answered on :8080. Tail of the boot log:"
    tail -20 "$BOOT_LOG" | sed 's/^/    /'
    SKIPPED+=("a clean boot under the local profile")
  fi
  kill "$BOOT_PID" 2>/dev/null || true
  wait "$BOOT_PID" 2>/dev/null || true
  note "full boot log: $BOOT_LOG"
fi
# ──────────────────────────────────────────────────────────────────────────

finish

note "backend:    ./mvnw spring-boot:run -Dspring-boot.run.profiles=local"
note "frontend:   cd frontend && npm start"
note "everything: ./scripts/run-all-tests.sh"
printf '\n'
